<a href="https://colab.research.google.com/github/BohdanShepel2005/Mashynne-Navchannya/blob/main/%D0%9C%D0%9D_%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%E2%84%961.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Встановлення бібліотеки NumPy (якщо потрібно)
# !pip install numpy

import numpy as np

# Завдання 1: Одновимірний масив із сумами поточного та попереднього числа
vector = np.cumsum(np.arange(1, 11))  # Беремо 10 елементів для прикладу
print("Завдання 1:", vector)

# Завдання 2: Матриця 3x3 з випадковими дійсними числами від 1 до 10
matrix_3x3 = np.random.uniform(1, 10, (3, 3))
print("\nЗавдання 2:\n", matrix_3x3)

# Завдання 3: Мінімальне значення в 3x3 матриці з випадковими числами 1-100
matrix_3x3_int = np.random.randint(1, 101, (3, 3))
min_value = np.min(matrix_3x3_int)
print("\nЗавдання 3:\n", matrix_3x3_int, "\nМінімальне значення:", min_value)

# Завдання 4: 4x4 матриця, підрахунок елементів > 0.5
matrix_4x4 = np.random.rand(4, 4)
count_greater_05 = np.sum(matrix_4x4 > 0.5)
print("\nЗавдання 4:\n", matrix_4x4, "\nКількість елементів > 0.5:", count_greater_05)

# Завдання 5: Поелементні операції на 1D масивах
array1 = np.random.randint(-10, 11, 4)
array2 = np.random.randint(-10, 11, 4)
sum_arrays = array1 + array2
diff_arrays = array1 - array2
print("\nЗавдання 5:\n", "Масив 1:", array1, "\nМасив 2:", array2,
      "\nСума:", sum_arrays, "\nРізниця:", diff_arrays)

# Завдання 6: Добуток двох 3x3 матриць
matrix_A = np.random.randint(1, 21, (3, 3))
matrix_B = np.random.randint(1, 21, (3, 3))
matrix_product = np.dot(matrix_A, matrix_B)
print("\nЗавдання 6:\n", "Матриця A:\n", matrix_A, "\nМатриця B:\n", matrix_B,
      "\nДобуток:\n", matrix_product)

# Завдання 7: Множення матриць 2x3 і 3x3
matrix_2x3 = np.random.randint(1, 5, (2, 3))
matrix_3x3 = np.random.randint(1, 5, (3, 3))
matrix_mult = np.dot(matrix_2x3, matrix_3x3)
print("\nЗавдання 7:\n", "Матриця 2x3:\n", matrix_2x3, "\nМатриця 3x3:\n",
      matrix_3x3, "\nРезультат множення:\n", matrix_mult)

# Завдання 8: Обернена матриця
matrix_3x3_inv = np.random.randint(1, 8, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3_inv)
print("\nЗавдання 8:\n", "Матриця:\n", matrix_3x3_inv, "\nОбернена матриця:\n",
      inverse_matrix)

# Завдання 9: Транспонування 4x4 матриці
matrix_4x4_bin = np.random.randint(0, 2, (4, 4))
transposed_matrix = matrix_4x4_bin.T
print("\nЗавдання 9:\n", matrix_4x4_bin, "\nТранспонована матриця:\n",
      transposed_matrix)

# Завдання 10: Множення 3x4 матриці на 4x1 вектор
matrix_3x4 = np.random.rand(3, 4)
vector_4x1 = np.random.rand(4, 1)
matrix_vector_product = np.dot(matrix_3x4, vector_4x1)
print("\nЗавдання 10:\n", "Матриця 3x4:\n", matrix_3x4, "\nВектор 4x1:\n",
      vector_4x1, "\nРезультат множення:\n", matrix_vector_product)

# Завдання 11: Множення 2x3 матриці на 3x1 вектор
matrix_2x3 = np.random.rand(2, 3)
vector_3x1 = np.random.rand(3, 1)
matrix_vector_product_2 = np.dot(matrix_2x3, vector_3x1)
print("\nЗавдання 11:\n", "Матриця 2x3:\n", matrix_2x3, "\nВектор 3x1:\n",
      vector_3x1, "\nРезультат множення:\n", matrix_vector_product_2)

# Завдання 12: Добуток елементів діагоналі
matrix_3x3_diag = np.random.randint(1, 6, (3, 3))
diag_product = np.prod(np.diag(matrix_3x3_diag))
print("\nЗавдання 12:\n", "Матриця:\n", matrix_3x3_diag, "\nДобуток діагоналі:",
      diag_product)

# Завдання 13: Різниця двох 4x4 матриць
matrix_4x4_A = np.random.randint(1, 6, (4, 4))
matrix_4x4_B = np.random.randint(1, 6, (4, 4))
matrix_diff = matrix_4x4_A - matrix_4x4_B
print("\nЗавдання 13:\n", "Матриця A:\n", matrix_4x4_A, "\nМатриця B:\n",
      matrix_4x4_B, "\nРізниця:\n", matrix_diff)

# Завдання 14: Найменший елемент у 3x3 матриці
matrix_3x3_min = np.random.randint(1, 11, (3, 3))
min_elem = np.min(matrix_3x3_min)
print("\nЗавдання 14:\n", matrix_3x3_min, "\nНайменший елемент:", min_elem)

# Завдання 15: Кількість ненульових елементів у кожному рядку
matrix_3x3_nonzero = np.random.uniform(-2, 2, (3, 3))
nonzero_counts = np.count_nonzero(matrix_3x3_nonzero, axis=1)
print("\nЗавдання 15:\n", "Матриця:\n", matrix_3x3_nonzero,
      "\nВектор-стовпчик ненульових елементів:\n", nonzero_counts)

# Висновок
"""
Виконано 15 завдань.
Я провів операції з масивами, матрицями, векторами, які включали:
- генерацію випадкових чисел,
- основні математичні операції,
- пошук діагоналей, транспонування та інверсію матриць.
"""







Завдання 1: [ 1  3  6 10 15 21 28 36 45 55]

Завдання 2:
 [[4.07055514 5.12351094 8.28287129]
 [8.99217352 3.64778571 9.52042887]
 [5.18820937 2.51786753 4.2801954 ]]

Завдання 3:
 [[10 16 65]
 [99  3 94]
 [22 19 38]] 
Мінімальне значення: 3

Завдання 4:
 [[0.61395706 0.45604906 0.45200907 0.43520297]
 [0.96674798 0.05545057 0.47101086 0.37957318]
 [0.13081388 0.90223138 0.06048351 0.82061343]
 [0.28484613 0.32812601 0.28347686 0.8492653 ]] 
Кількість елементів > 0.5: 5

Завдання 5:
 Масив 1: [-3  5  5  9] 
Масив 2: [ 0  3  7 -3] 
Сума: [-3  8 12  6] 
Різниця: [-3  2 -2 12]

Завдання 6:
 Матриця A:
 [[ 6 14 10]
 [ 9  6 17]
 [16  3  8]] 
Матриця B:
 [[10  1 11]
 [19  1 10]
 [ 9 18  4]] 
Добуток:
 [[416 200 246]
 [357 321 227]
 [289 163 238]]

Завдання 7:
 Матриця 2x3:
 [[3 4 1]
 [2 4 4]] 
Матриця 3x3:
 [[1 1 4]
 [3 1 4]
 [4 1 3]] 
Результат множення:
 [[19  8 31]
 [30 10 36]]

Завдання 8:
 Матриця:
 [[5 4 3]
 [7 4 2]
 [4 2 4]] 
Обернена матриця:
 [[-0.46153846  0.38461538  0.15384615]
 

'\nВиконано 15 завдань.\nЯ провів операції з масивами, матрицями, векторами, які включали:\n- генерацію випадкових чисел,\n- основні математичні операції,\n- пошук діагоналей, транспонування та інверсію матриць.\n'